# Generated by Django 3.2.6 on 2022-04-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('ПН', 'ПН'), ('ВТ', 'ВТ'), ('СР', 'СР'), ('ЧТ', 'ЧТ'), ('ПТ', 'ПТ'), ('СБ', 'СБ')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GroupNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('place_of_birth', models.CharField(default='не указан(а)', max_length=128)),
                ('adress', models.CharField(default='не указан(а)', max_length=128)),
                ('photo', models.ImageField(default='/media/photos/marc.jpg', upload_to='photos/')),
                ('data', models.DateField(default='')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fakultet')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(default='/media/photos/marc.jpg', upload_to='media/photos/')),
                ('place_of_birth', models.CharField(default='не указан(а)', max_length=128)),
                ('adress', models.CharField(default='не указан(а)', max_length=128)),
                ('data', models.DateField(default='')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fakultet')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profession')),
                ('students', models.ManyToManyField(to='home.Students')),
                ('subjects', models.ManyToManyField(default='', to='home.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(default='', to='home.Subjects'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.days')),
                ('group_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupnum')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.time')),
            ],
        ),
    ]
