# Generated by Django 3.2.6 on 2022-03-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='media/photos/')),
                ('data', models.DateField(default='')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fakultet')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='media/photos/')),
                ('data', models.DateField(default='')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fakultet')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profession')),
            ],
        ),
    ]
