# Generated by Django 3.2.6 on 2022-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(default='', to='home.Subjects'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(default='', to='home.Subjects'),
        ),
    ]
