# Generated by Django 3.2.6 on 2022-04-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnum',
            name='students',
            field=models.ManyToManyField(to='home.Students'),
        ),
        migrations.AddField(
            model_name='groupnum',
            name='teachers',
            field=models.ManyToManyField(to='home.Teachers'),
        ),
    ]
