# Generated by Django 3.2.6 on 2022-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220329_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(upload_to='static/assets/photos/'),
        ),
    ]
