# Generated by Django 3.2.6 on 2022-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_teachers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='students',
            field=models.ManyToManyField(to='home.Students'),
        ),
    ]
