# Generated by Django 3.2.6 on 2022-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teachers_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='adress',
            field=models.CharField(default='не указан(а)', max_length=128),
        ),
        migrations.AddField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(default='не указан(а)', max_length=128),
        ),
        migrations.AddField(
            model_name='teachers',
            name='adress',
            field=models.CharField(default='не указан(а)', max_length=128),
        ),
        migrations.AddField(
            model_name='teachers',
            name='place_of_birth',
            field=models.CharField(default='не указан(а)', max_length=128),
        ),
    ]
